export default {
    translation: {
        // COMMON TERMS
        name: "Nome",
        age: "Idade",
        gender: "Género",
        male: "Masculino",
        female: "Feminino",
        caregiver: "Cuidador",
        healthPro: "Profissional de Saúde",
        patient: "Paciente",
        yes: "Sim",
        no: "Não",
        language: "Idioma",
        languages: "Idiomas",
        portuguese: "Português",
        english: "Inglês",
        sort_by: "Ordenar por",
        filters: "Filtros",
        recent: "Recentes",
        old: "Antigos",
        cancel: "Cancelar",
        submit: "Submeter",
        search: "Pesquisar",
        private: "Privado",
        group: "Grupo",
        delete: "Apagar",
        title: "Título",
        category: "Categoria",
        content: "Conteúdo",
        color: "Cor",
        description: "Descrição",
        apps: "Aplicações",
        websites: "Websites",
        group: "Grupo",
        // LOGIN SCREEN
        login_welcome: "Bem-vindo/a de volta",
        login_subtext: "Vamos iniciar sessão e continuar a ajudar outros!",
        login_enter_email: "Introduzir e-mail",
        login_password: "Palavra-passe",
        login_forgot_password: "Esqueceu a palavra-passe",
        login: "Iniciar sessão",
        login_or: "ou",
        login_no_account: "Ainda não tem conta? ",
        login_sign_up: "Registe-se",
        login_toast_fail: "Erro: não foi possivel iniciar sessão",
        login_toast_missing_fields: "Por favor, preencha os campos de dados",
        message_error_recovery_password: "Erro ao recuperar palavra-passe",
        title_error_recovery_password: "Erro",

        // FORGOT PASSWORD SCREEN
        forgot_password: "Esqueceu-se da palavra-passe?",
        forgot_password_subtext: "Introduza o seu e-mail ou número de telemóvel para mudar a sua palavra-passe",
        forgot_password_input: "Introduza o e-mail ou número",
        forgot_password_send_code: "Enviar Código",

        // ENTER CODE SCREEN
        enter_code: "Introduza o seu código",
        enter_code_subtext: "Introduza o código que recebeu no seu e-mail ou telemóvel",
        enter_code_verify: "Verificar Código",
        enter_code_not_received: "Não recebeu o código? ",
        enter_code_resend: "Reenviar código",

        // ENTER NEW PASSWORD SCREEN
        new_password: "Definir nova palavra-passe",
        new_password_subtext: "A sua nova palavra-passe deve ser única para evitar que se esqueça dela :)",
        new_password_enter: "Introduzir nova palavra-passe",
        new_password_confirm: "Confirmar nova palavra-passe",
        new_password_reset: "Alterar Palavra-passe",

        // SUCCESS NEW PASSWORD SCREEN
        success_new_password_button: "Vamos começar!",

        // REGISTER SCREEN
        register_title: "Criar uma conta",
        register_subtext: "Vamos começar!",
        register_email: "Insira o seu e-mail",
        register_password: "Insira a sua palavra-passe",
        register_confirm_password: "Confirme a sua palavra-passe",
        register_continue: "Continuar",
        email_format_error: "Por favor insira um e-mail válido.",
        password_format_error: "A palavra-passe deve conter pelo menos oito caracteres, pelo menos uma letra maiúscula e minúscula, um número e um caractere especial.",
        register_no_fields: "Por favor preencha os campos de dados.",
        passwords_not_match: "As palavras-passe inseridas não correspondem.",

        // CREATE ACCOUNT SCREEN
        // title uses register_title
        create_account_role: "Que função lhe descreve melhor?*",
        create_account_share: "Partilhar a minha função*",
        create_account_phone: "Número de telemóvel",
        create_account_terms_begin: "Ao clicar em Vamos começar!, Registar com Google, ou Registar com Apple, concorda com os nossos ",
        create_account_terms_conditions: "Termos e Condições",
        create_account_terms_and: " e ",
        create_account_terms_privacy: "Declaração de Privacidade",
        create_account_mandatory: "* Campos obrigatórios.",
        create_account_button: "Vamos começar!",
        create_account_toast_success: "Conta criada com sucesso.",
        create_account_toast_error: "Erro na criação da conta.",

        // FEATURES SCREEN
        features_one: "Prepare-se para se conectar com pessoas, partilhar as suas experiências diárias, e falar em grupo ou em privado.",
        features_two: "Use o calendário para organizar o seu dia-a-dia, e manter-se a par dos seus compromissos, medicação e eventos.",
        features_three: "Fornecemos-lhe uma página com diversas ferramentas, como aplicações e websites, para lhe ajudar a lidar com a demência.",
        features_button: "Ir para Iniciar Sessão",

        // Navbar
        navbar_home: "Início",
        navbar_chat: "Chat",
        navbar_toolbox: "Toolbox",
        navbar_schedule: "Agenda",
        navbar_journal: "Diário",

        // HOMEPAGE SCREEN
        homepage_hello: "Olá",
        homepage_post_placeholder: "Que tens em mente?",
        homepage_like: "Gostar",
        homepage_comment: "Comentar",
        homepage_no_comments: "Sem comentários",
        homepage_toast_error_get_posts: "Erro ao tentar obter feed de notícias.",
        homepage_toast_error_login: "Erro: início de sessão falhado.",
        homepage_post_url_title: "Ligação URL", 
        homepage_post_url_message: "Por favor insira o URL inteiro da página web que deseja partilhar na sua publicação, incluindo ou \"https://\" ou \"http://\"",
        homepage_post_selected_image: "Imagem selecionada!",
        homepage_post_selected_video: "Vídeo selecionado!",
        homepage_menu_profile: "Perfil",
        homepage_menu_privacy_policy: "Política de Privacidade",
        homepage_menu_terms_use: "Termos de Utilização",
        homepage_menu_language: "Mudar para Inglês",
        homepage_menu_logout: "Terminar Sessão",
        homepage_write_comment: "Escreva um comentário...",
        homepage_comment_created: "Comentário criado com sucesso.",
        homepage_comment_error: "Erro ao criar comentário.",
        homepage_comment_get_error: "Ocorreu um erro ao tentar obter os comentários.",
        homepage_comment_see: "Ver ",
        homepage_comment_lowercase: "comentário",
        homepage_comments: "comentários",
        homepage_error_like: "Ocorreu um erro ao tentar gostar de uma publicação.",
        homepage_error_unlike: "Ocorreu um erro ao tentar tirar o gosto de uma publicação.",
        homepage_error_favorite: "Ocorreu um erro ao tentar meter uma publicação nos favoritos.",
        homepage_error_unfavorite: "Ocorreu um erro ao tentar tirar uma publicação dos favoritos.",

        // FILTERS
        filter_all: "Todos",
        filter_favorites: "Favoritos",
        filter_liked: "Gostados",
        // Caregiver filter uses 'caregiver'
        // Patient filter uses 'patient'
        // Health Professional filter uses 'healthPro'
        filter_unlabeled: "Sem função",

        // POST INPUT TRANSPARENT COMPONENT
        post_input_toast_created_post: "Criou uma nova publicação!",
        post_input_toast_error_post: "Erro ao criar publicação.",
        post_input_toast_created_comment: "Comentário criado.",
        post_input_toast_error_comment: "Erro a comentar na publicação.",
        post_input_toast_no_url: "Nenhum URL foi definido.",
        post_input_toast_url_https: "URL não contém \"http://\" nem \"https://\"",
        post_input_toast_url_valid: "URL válido definido!",
        post_input_toast_url_invalid: "URL definido, mas inválido.",

        // CHAT SCREEN
        chat_messages_unread: "mensagens não lidas",

        // TOOLBOX SCREEN
        toolbox_download_app: "Descarregar App",
        toolbox_visit_website: "Visitar Website",
        toolbox_pricing: "Preço",
        toolbox_free: "Gratuito",
        toolbox_most_stars: "Mais Estrelas",
        toolbox_least_stars: "Menos Estrelas",
        toolbox_most_languages: "Mais Idiomas",
        toolbox_least_languages: "Menos Idiomas",

        // JOURNAL SCREEN
        journal_toast_no_entries: "Não foram encontradas entradas.",
        journal_toast_entries_get_error: "Erro ao tentar obter entradas.",
        journal_toast_entry_characters: "Conteúdo deve conter pelo menos 50 caracteres.",
        journal_toast_created_entry: "Entrada criada com sucesso.",
        journal_toast_entry_deleted: "Entrada apagada com sucesso.",
        journal_begin_message: "Para começar a usar o diário, por favor crie uma nova entrada clicando no botão verde no canto inferior direito.",
        journal_entry_add_category: "Adicionar nova categoria",
        journal_create_entry: "Criar entrada",
        journal_entry_category_placeholder: "Selecione uma categoria",
        journal_create_category: "Criar categoria",
        journal_category_name: "Nome da categoria",
        journal_category_color: "Selecione uma cor",

        // MY SCHEDULE SCREEN
        schedule_previous: "Anterior",
        schedule_next: "Seguinte",
        schedule_export: "Exportar Agenda",
        schedule_monthly: "Mudar para Semanal",
        schedule_weekly: "Mudar para Mensal",
        schedule_create_event: "Criar Evento",
        schedule_select_calendar: "Selecionar agenda",
        schedule_event_date_time_start: "Selecione a data e hora de início",
        schedule_event_date_time_end: "Selecione a data e hora de fim",
        schedule_event_error_text1: "Erro",
        schedule_event_error_text2: "Erro ao criar evento",

        // PROFILE SCREEN
        profile_go_back: "Voltar Atrás",
        profile_edit: "Editar Perfil",

        // MONTHS
        january: "Janeiro",
        february: "Fevereiro",
        march: "Março",
        april: "Abril",
        may: "Maio",
        june: "Junho",
        july: "Julho",
        august: "Agosto",
        september: "Setembro",
        october: "Outubro",
        november: "Novembro",
        december: "Dezembro",
        
        january_short: "Jan",
        february_short: "Fev",
        march_short: "Mar",
        april_short: "Abr",
        may_short: "Mai",
        june_short: "Jun",
        july_short: "Jul",
        august_short: "Ago",
        september_short: "Set",
        october_short: "Out",
        november_short: "Nov",
        december_short: "Dez",

        // DAYS
        sunday: "Domingo",
        monday: "Segunda",
        tuesday: "Terça",
        wednesday: "Quarta",
        thursday: "Quinta",
        friday: "Sexta",
        saturday: "Sábado",
        
        sunday_short: "Dom",
        monday_short: "Seg",
        tuesday_short: "Ter",
        wednesday_short: "Qua",
        thursday_short: "Qui",
        friday_short: "Sex",
        saturday_short: "Sáb",
        today: "Hoje",
    }
}